name: 提取boot


on:
  workflow_dispatch:
    inputs:
      rom_url:
        description: 'ROM 下载直链'
        required: true
        default: ''
      rom_name:
        description: '保存名称'
        required: true
        default: ''
jobs:
  YIJIANTIQU:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@main

      - name: 安装依赖
        run: |
         sudo apt-get update
         sudo apt-get -y install python3-pip
         sudo apt install aria2
         
      - name: tongbu
        run: |
         curl https://rclone.org/install.sh | sudo bash
         mkdir -p ~/.config/rclone/
         unzip -o rclone.zip -d ~/.config/rclone/

      - name: 提取镜像
        run: |
         ls
     
