name: 小米zip提取

on:
  workflow_dispatch:
    inputs:
      rom_url:
        description: 'ROM 下载直链'
        required: true
        default: ''
      rom_name:
        description: '保存名称'
        required: true
        default: ''

jobs:
  mi_zip:
    runs-on: ubuntu-24.04
    steps:
      - name: 检出代码
        uses: actions/checkout@main

      - name: 安装依赖
        run: |
          sudo apt-get update
          sudo apt-get -y install python3-pip aria2 p7zip curl
          curl https://rclone.org/install.sh | sudo bash

      - name: 配置 rclone
        run: |
          mkdir -p ~/.config/rclone
          unzip -o rclone.zip -d ~/.config/rclone/

      - name: 下载固件
        run: |
          mkdir -p "${GITHUB_WORKSPACE}/workspace/output" && cd "${GITHUB_WORKSPACE}/workspace"
          aria2c -s 10 -x 10 -d . -o firmware.zip "${{ github.event.inputs.rom_url }}"
          7z x firmware.zip -o"${GITHUB_WORKSPACE}/workspace/output" boot.img vbmeta.img

      - name: 压缩并上传文件
        run: |
          cd "${GITHUB_WORKSPACE}/workspace/output"
          7z a "${{ github.event.inputs.rom_name }}.zip" -p"${{ secrets.UNZIP_PASSWORD }}" *
          7z a "${{ github.event.inputs.rom_name }}.zip" /home/runner/work/boot/boot/获取解压密码.txt
          rclone sync "${{ github.event.inputs.rom_name }}.zip" 123:/zanfang
          
