name: 上传

on:
  workflow_dispatch:
    inputs:
      url:
        description: '下载链接'
        required: true
        default: ''
      name:
        description: '保存名称(带后缀)'
        required: true
        default: ''
      dizhi:
        description: '保存地址'
        required: true
        default: ''

jobs:
  up:
    runs-on: ubuntu-24.04

    steps:
      - name: 检出代码
        uses: actions/checkout@main

      - name: 信息输出
        run: |
         echo "输入名称：${{ github.event.inputs.name }}"
         echo "下载链接：${{ github.event.inputs.url }}"

      - name: 安装依赖
        run: |
         sudo apt-get update
         sudo apt-get install -y python3-pip aria2 p7zip unzip

      - name: 同步上传
        run: |
         curl https://rclone.org/install.sh | sudo bash
         mkdir -p ~/.config/rclone/
         unzip -o rclone.zip -d ~/.config/rclone/

      - name: 下载文件
        run: |
         mkdir -p ${GITHUB_WORKSPACE}/workspace
         cd ${GITHUB_WORKSPACE}/workspace
         
         # 使用 aria2c 下载文件
         aria2c -s 16 -x 16 -d . -o "${{ github.event.inputs.name }}" "${{ github.event.inputs.url }}" || { echo "aria2c 下载失败"; exit 1; }

      - name: 同步上传至目标位置
        run: |
         # 确保上传前下载完成
         if [ -f "${{ github.event.inputs.name }}" ]; then
           rclone sync "${{ github.event.inputs.name }}" 123:/${{ github.event.inputs.dizhi }} || { echo "rclone 上传失败"; exit 1; }
         else
           echo "下载的文件不存在，上传失败"
           exit 1
         fi

      - name: 清理临时文件
        run: |
         rm -rf ${GITHUB_WORKSPACE}/workspace
