name: zip提取

on:
  workflow_dispatch:
    inputs:
      rom_url:
        description: 'ROM 下载直链'
        required: true
        default: ''
      rom_name:
        description: '保存名称'
        required: true
        default: ''

jobs:
  zip:
    runs-on: ubuntu-24.04
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 信息输出
        run: |
          echo "输入名字：${{ github.event.inputs.rom_name }}"
          echo "下载链接：${{ github.event.inputs.rom_url }}"

      - name: 安装依赖
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip aria2 p7zip-full curl

      - name: 配置 rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash
          mkdir -p ~/.config/rclone/
          echo "${{ secrets.RCLONE_CONFIG }}" > ~/.config/rclone/rclone.conf

      - name: 提取镜像
        run: |
          set -e
          mkdir -p ${GITHUB_WORKSPACE}/workspace
          cd ${GITHUB_WORKSPACE}/workspace
          
          # 下载固件
          aria2c -s 16 -x 16 -d . -o firmware.zip "${{ github.event.inputs.rom_url }}"
          
          # 解压文件
          7z e firmware.zip "boot.img" "init_boot.img" "vbmeta.img" -r -ooutput || exit 1
          
          # 压缩并加密
          cd output
          7z a "${{ github.event.inputs.rom_name }}.zip" -p"${{ secrets.UNZIP_PASSWORD }}" *
          7z a "${{ github.event.inputs.rom_name }}.zip" /home/runner/work/boot/boot/获取解压密码.txt

      - name: 同步上传
        run: |
          rclone sync "${{ github.event.inputs.rom_name }}.zip" "${{ secrets.RCLONE_REMOTE }}:/boot大全"
