name: payload提取

on:
  workflow_dispatch:
    inputs:
      rom_url:
        description: 'ROM 下载直链'
        required: true
      rom_name:
        description: '保存名称'
        required: true

jobs:
  TIQU:
    runs-on: ubuntu-24.04
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 安装依赖
        run: |
          sudo apt-get update
          sudo apt-get -y install python3-pip aria2 p7zip-full
          curl https://rclone.org/install.sh | sudo bash

      - name: 配置 rclone
        run: |
          mkdir -p ~/.config/rclone/
          echo "${{ secrets.RCLONE_CONFIG }}" > ~/.config/rclone/rclone.conf

      - name: 提取镜像
        run: |
          mkdir -p ${GITHUB_WORKSPACE}/workspace && cd ${GITHUB_WORKSPACE}/workspace
          pip install git+https://github.com/5ec1cff/payload-dumper
          aria2c -s 10 -x 10 -d . -o firmware.zip "${{ github.event.inputs.rom_url }}"
          payload_dumper --partitions boot,vbmeta,init_boot firmware.zip
          cd output
          # 生成解压密码文件
          echo ${{ secrets.UNZIP_neirong }} > 解压密码.txt
          # 压缩提取的分区内容（加密）
          7z a "../${{ github.event.inputs.rom_name }}_encrypted.zip" -p"${{ secrets.UNZIP_PASSWORD }}" *
          # 压缩解压密码文件（不加密）
          7z a "../${{ github.event.inputs.rom_name }}_password.txt.zip" 解压密码.txt

      - name: 合并 ZIP 文件
        run: |
          cd ${GITHUB_WORKSPACE}/workspace
          zip -j "${{ github.event.inputs.rom_name }}.zip" ./*.zip

      - name: 上传文件到远程
        run: |
          rclone sync "${GITHUB_WORKSPACE}/workspace/${{ github.event.inputs.rom_name }}.zip" 123:/boot大全